int menu();
struct Series* add(struct Series*, int);
struct Series* del(struct Series*, int);
void search(struct Series*, int);
void show(struct Series*, int);
void print(struct Series*, int, int);
int check(int);
void printLine();
int size(struct Series*, int);
void deleteEnter(struct Series*, int, int, int);
void search(struct Series*, int);
struct Series* delExact(struct Series*, int, int);
struct Series* deleteByTheOption(struct Series*, int);
void sortFromMin(struct Series*, int);
void sortFromMax(struct Series*, int);
void sort(struct Series*, int);
struct Series* change(struct Series*, int);
void partSearch(struct Series*, int);
void findCharNumber(struct Series*, int, int);
void rightRegister(struct Series*, int, int);